spring:
  application:
    name: cadence-transcoder
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: ${CADENCE_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true
    consumer:
      group-id: cadence-transcoder
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: ${CADENCE_TRANSCODER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
